baseURL = "https://gongled.ru/"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
title = "Сайт Глеба Гончарова"
theme = "simple"
avatar = "userpic.jpg"
staticDir = ["static"]

[languages]
  [languages.ru]
    title = "Глеб Гончаров"
    weight = 1
    [languages.ru.params]
      author = "Глеб Гончаров"
      description = "Юнит лид в СберМаркете."
      email = "inbox@gongled.ru"
      videoURL = "https://static.gongled.ru/video/"
      nickname = "gongled"
      locale = "ru-RU"
  [languages.en]
    title = "Gleb Goncharov"
    weight = 2
    [languages.en.params]
      author = "Gleb Goncharov"
      description = "Unit Lead in SberMarket."
      email = "inbox@gongled.ru"
      videoURL = "https://static.gongled.ru/video/"
      nickname = "gongled"
      locale = "en-US"

[build]
  writeStats = true

[permalinks]
  blog = "/blog/:filename/"
  work = "/work/:filename/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4
